### ISSUE TITLE
Ojo

### ISSUE THREAD

**Issue by LeonelYLuego** [san-lpz/san-lpz#1]
Ya toda una desarrolladora?

**Comment by ShariZhari** [comment]
xd aún no jajaj
por??

**Comment by LeonelYLuego** [comment]
Por todas tus habilidades que pusiste

**Comment by ShariZhari** [comment]
xd esto ya está bien viejo, tiene desde el año pasado

**Comment by LeonelYLuego** [comment]
Andabas actualizando los códigos?
